user nginx;
http {

	server {
		server_name localhost;
		listen 8080;
		return 301 http://$host:8443$request_uri
	}

	server {
		server_name localhost;
		listen 8443 ssl;
		ssl_protocols TLSv1.3;
		ssl_certificate /certs/certs.pem;
		ssl_certificate_key /certs/key.pem;

		location / {
			proxy_pass http://frontend:3000;
		}

		location /api {
			proxy_pass http://backend:3001;
		}

		location /ws {
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_pass http://backend:3001;
		}

	}
}
